"""empty message

Revision ID: 884c5288ccb3
Revises: 2fdffd8ced04
Create Date: 2018-02-09 21:12:37.095165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884c5288ccb3'
down_revision = '2fdffd8ced04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
